[versions]
hikarycp = "6.3.0"
lombok = "1.18.30"
minecraft = "1.20.1-R0.1-SNAPSHOT"

[libraries]
hikarycp = {group = "com.zaxxer", name = "HikariCP", version.ref = "hikarycp"}
lombok = {group = "org.projectlombok", name = "lombok", version.ref = "lombok"}
minecraft-api = {group = "dev.folia", name = "folia-api", version.ref = "minecraft"}